# ------------------------------------------------------------------
# ----------------------- Official Release -------------------------
# ------------------------ CREATOR: oTrixzy ------------------------
# -------------------------- Version: 1.3 --------------------------
# -------------------- Released Date: 7/21/2024 --------------------
# --------- Github: github.com/TrixzyMc/oTrixzy-Portfolio/ ---------
# ------------------------------------------------------------------

# Removed Vault Suffix, added custom variable and placeholder: Requires skript-placeholders for var's. 

options:
	prefix: <##B022EC>&lᴄʜᴀᴛᴄᴏʀᴇ &8» 

on load:
	# All deletes are required for the skript to work, Don't worry when it will reloads it will reload all chat colors.
	delete {ChatCore::ChatColor::Registered::*} 
	delete {ChatCore::ChatTags::Registered::*}
	delete  {ChatCore::ExampleTexts::*}
	
	# Feel free to delete this, Only gets sent to server administrators. EG. People with Permission ChatCore.Admin.
	send "{@prefix} &fAll chat colors & chat tags have been reloaded." to all players where [input has permission "ChatCore.Admin"]

# If you have skript-placeholders & placeholderapi uncomment this and you can do %chatcore_suffix% to get the player's suffix (for tab, etc)
#placeholderapi placeholder with the prefix "chatcore":
	#if the identifier is "suffix": 
		#if {ChatCore::ChatTags::PlayerTags::%player's uuid%} is set:
			#set the result to "%{ChatCore::ChatTags::PlayerTags::%player's uuid%}% "
		#else:
			#set the result to ""
		
# [!] Do not move this up, You shall touch. [!]
on load:

	# Use <gradient:##ffffff:##000000> for gradients
	# Use <#ffffff> for hexcodes
	# Use &f for legacy codes
	
	# Must use MINI MESSAGE formats for the <gradient:##ffffff:##000000> for example <dark_gray> for dark gray. This is not handled
	# Put <bold> in front of gradient names to make the text bold
	# Put &l in front of hexcode / legacy code names to make it bold.
	#       THIS WILL NOT MAKE THE CHAT COLOR BOLT ITSELF, PUT IT IN THE COLOR STRING TO DO THAT.
	registerColor(1, "&lᴡʜɪᴛᴇ", "chatCore.color.white", "<#ffffff>")
	registerColor(2, "<bold>ʙʟᴜᴇ ɪᴄᴇ", "chatCore.color.blueIce", "<gradient:#A9FFFF:#00AAFF>")
	registerColor(3, "<bold>sᴜɴsᴇᴛ", "chatCore.color.sunset", "<gradient:#FF7A18:#FF3D81>")
	registerColor(4, "<bold>ᴍɪɴᴛ", "chatCore.color.mint", "<gradient:#7CFFCB:#2FE6A6>")
	registerColor(5, "<bold>ʀᴏʏᴀʟ", "chatCore.color.royal", "<gradient:#7B7BFF:#3B3BFF>")

	registerTag(1, "&f☁ &8•", "chatCore.tags.Cloud")
	registerTag(2, "<#ECAD22>⚡ &8•", "chatCore.tags.Lightning")
	registerTag(3, "<#2261EC>❄ &8•", "chatCore.tags.Frost")
	registerTag(4, "&e✦ &8•", "chatCore.tags.Star")
	registerTag(5, "<gradient:#FF9A9E:#FAD0C4>❤ <dark_gray>•", "chatCore.tags.Heart")
	registerTag(6, "<#2261EC>🦈 &8•", "chatCore.tags.Shark")
	
	registerExampleText("Charming!")
	registerExampleText("Tidy!")
	registerExampleText("Fantastic!")
	registerExampleText("Fancy!")
	registerExampleText("Stylish!")
	
	# --->> DO NOT TOUCH BELOW, SUPPORT WILL NOT BE GIVEN. <<--- ##

# --> Functions to register Color / Tags. <-- #
function registerColor(id: integer, name: string, requiredPermission: string, colorHex: string):

	set {ChatCore::ChatColor::Registered::%{_id}%} to true

	set {ChatCore::ChatColor::Registered::%{_id}%::name} to {_name}
	set {ChatCore::ChatColor::Registered::%{_id}%::color} to {_colorHex}
	set {ChatCore::ChatColor::Registered::%{_id}%::lore} to " %{_colorHex}%<bold>| %{_colorHex}%Lore Coming Soon..."
	set {ChatCore::ChatColor::Registered::%{_id}%::requiredPermission} to {_requiredPermission}

function registerTag(id: integer, tag: string, required-permission: string):
	set {ChatCore::ChatTags::Registered::%{_id}%} to true

	set {ChatCore::ChatTags::Registered::%{_id}%::name} to {_tag}
	set {ChatCore::ChatTags::Registered::%{_id}%::requiredPermission} to {_required-permission}

function registerExampleText(text: string):
	add {_text} to {ChatCore::ExampleTexts::*}
	
# --> Functions to create GUIS <-- #

function getRandomExampleText():: string:
	set {_random} to random integer between 1 and size of {ChatCore::ExampleTexts::*}
	return {ChatCore::ExampleTexts::%{_random}%}
	
function ChatTags(p: player, page: number=1):
	set {_name} to "<#B022EC>ChatTags <dark_gray>(<#6E97D7>#%{_page}%<dark_gray>)"
	create a gui with virtual chest inventory with 5 rows named "%{_name}%":
		make gui slot (all integers between 0 and 44) with black stained glass pane named "&7" without entire tooltip
		make gui slot (all integers between 10 and 16, all integers between 19 and 25, all integers between 28 and 34) with stone button named "&7" without entire tooltip
		make gui slot 4 with knowledge book named "" with all item flags
		make gui slot 40 with barrier named "&cʀᴇᴍᴏᴠᴇ ᴛᴀɢ" with all item flags:
			if {ChatCore::ChatTags::PlayerTags::%player's uuid%} is not set:
				close player's inventory
				send "{@prefix} &fYou do not have a chat tag equipped." to player
				stop
			
			delete {ChatCore::ChatTags::PlayerTags::%player's uuid%}
			send "{@prefix} &fRemoved your current tag." to player
			stop
		set {_start_index} to ({_page} - 1) * 21 + 1
		set {_end_index} to {_page} * 21
		
		if {_page} > 1:
			make gui slot 36 with strong healing tipped arrow named "&cʙᴀᴄᴋ ᴘᴀɢᴇ" with all item flags:
				ChatTags({_p}, ({_page} - 1))
		
		
		set {_slot} to 10

		loop all integers between {_start_index} and {_end_index}:
			exit loop if {ChatCore::ChatTags::Registered::%loop-value%} is not set
			
			set {_text} to formatted "&f%{ChatCore::ChatTags::Registered::%loop-value%::name}%"
			if {_p} has permission "%{ChatCore::ChatTags::Registered::%loop-value%::requiredPermission}%":
				set {_i} to name tag of mending named "%{_text}%"  with all item flags
				
				set {_lore::*} to "&8ᴛᴀɢs"
				add "%nl%%{_text}% <#B022EC>%{_p}% &8»&f %getRandomExampleText()%" to {_lore::*}
				add "%nl%<#B022EC>ᴄʟɪᴄᴋ ᴛᴏ ᴇǫᴜɪᴘ" to {_lore::*}
				make gui slot {_slot} with {_i} with lore {_lore::*}:
					set {ChatCore::ChatTags::PlayerTags::%player's uuid%} to {_text}
					close player's inventory
					send action bar "{@prefix} &fYou equipped the tag %{_text}%&f!"
					
			add 1 to {_slot}
			
			if loop-value >= 21:
				make gui slot 44 with strong swiftness tipped arrow named "&bɴᴇxᴛ ᴘᴀɢᴇ" with all item flags:
					ChatTags({_p}, ({_page} + 1))
			
			if {_slot} = 17 or 26 or 35:
				add 2 to {_slot}

	open last gui to {_p}

function ChatColor(p: player, page: number=1):
	create a gui with virtual chest inventory with 5 rows named "ChatColor (Page #%{_page}%)":
		make gui slot (all integers between 0 and 44) with black stained glass pane named "&7" without entire tooltip 
		make gui slot (all integers between 10 and 16, all integers between 19 and 25, all integers between 28 and 34) with stone button named "&7" without entire tooltip
		make gui slot 4 with knowledge book named "" with all item flags
		set {_start_index} to ({_page} - 1) * 21 + 1
		set {_end_index} to {_page} * 21
		
		if {_page} > 1:
			make gui slot 36 with strong healing tipped arrow named "&cʙᴀᴄᴋ ᴘᴀɢᴇ" with all item flags:
				ChatColor({_p}, ({_page} - 1))

		set {_slot} to 10

		loop all integers between {_start_index} and {_end_index}:
			exit loop if {ChatCore::ChatColor::Registered::%loop-value%} is not set
			set {_color} to {ChatCore::ChatColor::Registered::%loop-value%::color}
		
			set {_preview} to formatted "&f%{_color}%%getRandomExampleText()%"
			set {_text} to formatted "&f%{_color}%%{ChatCore::ChatColor::Registered::%loop-value%::name}%"
			
			if {_p} has permission {ChatCore::ChatColor::Registered::%loop-value%::requiredPermission}:
				set {_i} to name tag of mending named "%{_text}%"  with all item flags
				
				set {_lore::*} to "&8ᴛᴀɢs"
				add "%nl%<#B022EC>%{_p}% &8» %{_preview}%" to {_lore::*}
				add "%nl%<#B022EC>ᴄʟɪᴄᴋ ᴛᴏ ᴇǫᴜɪᴘ" to {_lore::*}
				make gui slot {_slot} with {_i} with lore {_lore::*}:
					set {ChatCore::ChatColor::PlayerColor::%{_p}'s uuid%} to {_color}
					close player's inventory
					send action bar "{@prefix} &fYou equipped the color %{_text}%&f!"
					
			add 1 to {_slot}
			
			if loop-value >= 21:
				make gui slot 44 with strong swiftness tipped arrow named "&bɴᴇxᴛ ᴘᴀɢᴇ" with all item flags:
					ChatColor({_p}, ({_page} + 1))
			
			if {_slot} = 17 or 26 or 35:
				add 2 to {_slot}

	open last gui to {_p}

function formatColor(prefix: text) :: text:
	set {_result} to {_prefix}
	replace regex "&#([A-Fa-f0-9]{6})" with "<#$1>" in {_result}
	
	return {_result}

on chat:
	loop all players:
		if message contains "%loop-player%":
			replace "%loop-player%" with "&e&l@%loop-player%%{ChatCore::ChatColor::PlayerColor::%player's uuid%}%" in message
			play sound "BLOCK_NOTE_BLOCK_PLING" with volume 0.4 and pitch 1 to loop-player
			send action bar "&aʏᴏᴜ ʜᴀᴠᴇ ʙᴇᴇɴ ᴘɪɴɢᴇᴅ ɪɴ ᴄʜᴀᴛ" to loop-player
		
	replace message with formatted "%{ChatCore::ChatColor::PlayerColor::%player's uuid%} ? "&7"%%message%" in message
	set {_prefix} to formatColor(colored player's prefix)
	set {_suffix} to ""
	set {_suffix} to "%formatColor({ChatCore::ChatTags::PlayerTags::%player's uuid%})% " if {ChatCore::ChatTags::PlayerTags::%player's uuid%} is set
	set chat format to colored "%{_suffix}%<bold>%{_prefix}%<reset> &f%player's display name% &8» %message%"
		
# --> Commands <-- #
command /chatcolor:
	trigger:
		ChatColor(player)

command /tags:
	trigger:
		ChatTags(player)

